# Generated by Django 4.2.6 on 2025-01-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="bangla",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="caption",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="content",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
