# Generated by Django 4.2.6 on 2025-01-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_content_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
