# Generated by Django 4.2.6 on 2025-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0007_content_font"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="font",
            field=models.CharField(
                choices=[
                    ("AdorNoirrit", "AdorNoirrit"),
                    ("AlinurNakkhatra", "AlinurNakkhatra"),
                    ("AlinurShowpnocari", "AlinurShowpnocari"),
                    ("Sankalpa", "Sankalpa"),
                    ("SirajeeSanjar", "SirajeeSanjar"),
                    ("SwarnaliOkkhor", "SwarnaliOkkhor"),
                ],
                default="Normal",
                max_length=50,
            ),
        ),
    ]
