# Generated by Django 4.2.6 on 2025-01-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
